### ISSUE TITLE
Possibility to show a dataset that is still not open

### ISSUE THREAD

**Issue by epaiva** [ckan/ckanext-qa#34]
We wanted to use ckan to make public the inventory of datasets of a public organization (even the ones that are still not open). This way we would be transparent regarding existing datasets and be able to prioritize the opening process taking into account the interest and demand of citizens.

However, we are concerned with communicating this clearly. In this sense, this extension could address this showing not only the level of maturity of open datasets, but also that some datasets exist but are still not open (no stars or other visual solution). This could solve our concern.

**Comment by davidread** [comment]
Yes a dataset that has not been published will have no resource URL will receive 0 stars. e.g. on data.gov.uk we show such datasets like this: https://data.gov.uk/dataset/sheep-and-goats-annual-inventory

If you have ideas for communicating this better then do suggest something.
