### ISSUE TITLE
Celery Queues in stock CKAN ?

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckanext-qa#37]
By default CKAN creates single celery queue, ckanext-qa and ckanext-archiver use queue named bulk if no queues are given in paster command. Does these extensions actually work with stock CKAN ?

In opendata.fi we cherry-picked ckan commit from data.gov.uk which enabled defining multiple queus https://github.com/yhteentoimivuuspalvelut/ckan/commit/85ef19c73faa7e841e9e0b94ec1044dbb6fee389 but we do not actually want to support this method in our new instances. 

Celery is deprecated in future CKAN but we need to get these extension work for now, so is this just a configuration error in our end or should these work with CKAN 2.5.2 ?

**Comment by davidread** [comment]
Does this alternative way of starting celery solve it? The command is in ckanext-archiver, which is required for ckanext-qa.

paster --plugin=ckanext-archiver celeryd2 run all -c development.ini

**Comment by Zharktas** [comment]
Hi,

that actually did solve, might be good idea to to document it to ckanext-qa too :)

**Comment by davidread** [comment]
Great to hear it. I've added a note in the readme now. Thanks :)
