### ISSUE TITLE
Move openness-element outside of organization.html-snippet or contain it in a block

### ISSUE THREAD

**Issue by mikkonieminen** [ckan/ckanext-qa#38]
Why is the element with the openness stars inside snippets/organization.html? Could it be moved to package/snippets/info.html for easier customization since it is not related to the organization at all?

Or could the code be contained in a block so that it could be overwritten more easily elsewhere?

**Comment by davidread** [comment]
We want the stars to show on the package read page on the sidebar, between the info about the organization and the social links. With the existing package/read_base.html template, the choice is either to replace the entire side bar block `secondary_content` or we attach it to either `package_organization` or `package_social`, and I just went for the `package_organization` block, which is defined in snippets/organization.html.

Does it still work if you move it to info.html, like you say?

Is the problem with you overwriting snippets/organization.html again is that it is being overwritten twice and it only works if you load the extensions in the right order? If that's the case then maybe adding another layer of blocks would work.

Feel free to play around to see what works and suggest a PR.

**Comment by mikkonieminen** [comment]
Provided a [pull request](https://github.com/ckan/ckanext-qa/pull/39). This solution requires minimal effort and still provides the customizability I mentioned above.
