### ISSUE TITLE
HelperError: relative_url_for has not been defined in openness.html line 40

### ISSUE THREAD

**Issue by mixedbredie** [ckan/ckanext-qa#40]
I get an internal server error when I hit my /report/openness link and the error log has the following in it:

```
File '/usr/lib/ckan/default/src/ckanext-qa/ckanext/qa/templates/report/openness.html', line 40 in top-level template code
  <td>{{ h.link_to(row['organization_title'], h.relative_url_for(organization=row['organization_name'])) }}</td>
File '/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py', line 412 in getattr
  return obj[attribute]
File '/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py', line 62 in __getitem__
  key=key
HelperError: Helper 'relative_url_for' has not been defined.
```

I am running 2.6.0 on Ubuntu 14.04 an have the latest version of the QA, Report and Archiver plugins installed.

**Comment by brunopenteado** [comment]
The same happens to me. Did you manage to fix it?

**Comment by mixedbredie** [comment]
I'll be able to test the fix in #42 tomorrow when I am back on the box.

**Comment by mixedbredie** [comment]
Yes, that fixes the error.  Thank you very much.

**Comment by davidread** [comment]
@mixedbredie Many thanks for reporting this and checking the fix. Much appreciated.

**Comment by brunopenteado** [comment]
That worked! Thanks
